#ifndef CSE356HEADER_H_
#define CSE356HEADER_H_
#include <stdio.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
#include <wait.h>
#include <signal.h>
#include <sstream>
#include <pthread.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <ctype.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <netdb.h> 
#include <sys/mman.h>
#include <fcntl.h>
#include <math.h>
#endif/*CSE356HEADER_H_*/
